version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: cregistry
      MYSQL_USER: test
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: pw
networks:
  springapimysql-net: